### ISSUE TITLE
Quotation marks 

### ISSUE THREAD

**Issue by Dimon-II** [jrathlev/SynEdit-Spell-Checker#4] opened 2024-03-21 09:10 UTC
Some types of quotation marks (despite the AdditionalWordBreakChars specified in the code) are not separated from the word.
This is more of a Synedit problem, but it can’t be fixed without interfering with the source code. 
Maybe do an additional analysis of AdditionalWordBreakChars or own similar attribute in the spell checker? 
```
 TDrawAutoSpellCheckPlugin.Create(SynEditor,MainData.SynEditSpellCheck);
 SynEditor.Highlighter.AdditionalWordBreakChars:=['«', '»', '“', '”'];
 SynEditor.AdditionalWordBreakChars:=['«', '»', '“', '”'];
```
_“Production is up, costs are down, the rivers are full. Time to talk expansion.”_

![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/a51010c7-3701-42e2-ad99-c9a87efb4d90)

**Comment by jrathlev** [comment] 2024-03-23 12:03
Did you try to set SynEditor.AdditionalIdentChars?

**Comment by Dimon-II** [comment] 2024-03-23 17:55
No, the situation is the opposite - the "AdditionalIdentChars" are added to the selected word.
For sample, when I need select macro [str] with brackets, i can add '[', ']' to AdditionalIdentChars. This word is highlighted by double-click and auto-completion and rightly so.

But when checking spelling, I can't exclude certain types of quotation marks.
That is, [“ Left Double Quotation Mark](https://www.utf8icons.com/character/8220/left-double-quotation-mark)  becomes part of the word and is considered a spelling error.

**Comment by jrathlev** [comment] 2024-03-23 22:08
Checking the Synedit code, I found that no Unicode characters are supported for "AdditionalIdentChars" and "AdditionalWordBreakChars". The program uses the function "CharInSet" which only works for ASCII characters (0..255).

**Comment by Dimon-II** [comment] 2024-03-24 09:19
The function has two implementations:
function CharInSet(**C: AnsiChar**; const CharSet: TSysCharSet): Boolean;
function CharInSet(**C: WideChar**; const CharSet: TSysCharSet): Boolean;
The problem is a little deeper - in the type type TSysCharSet = **set of AnsiChar;**
And the Set type does not allow working with values greater than 255...

That is, without a big modification to synedit (make AdditionalWordBreakChars a string and check as **pos(C,AdditionalWordBreakChars)>0**) this cannot be fixed.

Can this additional analysis be done in a spell check?

**Comment by jrathlev** [comment] 2024-03-24 12:57
There is no big modification of Synedit required. I changed TSysCharSet to TCharArray and CharInSet to CjarInArray in the units Synedit.pas and SynEditHighlighter.pas. Sources are provided in the subdirectory synedit.
Please check if this will work for your application.

**Comment by Dimon-II** [comment] 2024-03-24 20:19
Thanks, it works with these fixes. 
I also fixed your files a little - added an interface for removing (erroneously added) words from the user dictionary.
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/ccbefb49-2a64-4f64-b454-a72fb3a8089b)
...I didn’t want to make corrections to a third-party library - my project is also posted in the source code and there’s just a link to synedit. https://github.com/Dimon-II/DeCard64

**Comment by jrathlev** [comment] 2024-03-25 18:45
I added the lines from your source to erase words from dictionary. But the selected word is not removed from the hunspell internal dictionary (only from the FUserDict string list). "HunspellRemove" seems not work. Do you have amy idea?

**Comment by Dimon-II** [comment] 2024-03-25 20:05
Erase menu is active only for words from the user dictionary.
  procedure TSynEditSpellCheck.EraseDictWord (const AWord : String);
  if FEnabled and Assigned(FHunspellHandle) and (length(sw)>0) then **with FUserDict do if IndexOf(sw)>-1** then begin


The dictionaries are assumed to be correct, and errors can only occur in the user dictionary. Words are added and removed only to user dictionaries. Saving a custom dictionary is a feature of your project.
I write a custom dictionary to my project (that is, each project can have its own dictionary) from this FUserDict, I only needed the delete function to restore this word highlighting without completely reloading the dictionaries.

After calling this function for a word from the user dictionary, the word is highlighted as containing an error.
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/25ccf4e6-6e3d-485e-b397-822d5d3b8b15)
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/a2b97212-f468-4845-8734-a8080dc6703e)
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/c5130590-66c5-4526-82d2-bd405d5913f5)

PS Mb you copy line where I PREVENT YOUR SAVING dictionary?
`  MainData.SynEditSpellCheck.Modified := False;
`

**Comment by jrathlev** [comment] 2024-03-26 18:48
You sholud not set _Modified_ to false because in this case words earlier added to the user dictionary will not be saved.

My problem is that a removed word is **not marked as error** afterwards. This is not an issue with the user dictionary list but with the _HunspellRemove_ function. Which hunspell dll library do you use?

**Comment by Dimon-II** [comment] 2024-03-26 19:12
Hunspellx64.dll from your package
![image](https://github.com/jrathlev/SynEdit-Spell-Checker/assets/29166758/dd1053e0-4b6d-4702-b71b-39bbce50edae)

**Comment by Dimon-II** [comment] 2024-03-26 21:09
> a

Looks like you have a problem with your German dictionary! When English is selected in your demo project, it is normally added and removed from the dictionary with highlighting in the editor.

**Comment by jrathlev** [comment] 2024-03-27 10:58
You are right. It depends on the selected dictionary, but the cause remains unclear. I tested different dictionaries, e.g. the one from LibreOffice. The HunspellRemove function does not work for all of them.

**Closed as completed** 2024-03-31 11:27 UTC
